<#
    install.ps1
    Registers the watchdog to start with Windows and starts it right away.

    The Startup entry is a .vbs rather than a .bat because the .vbs can start
    PowerShell with a hidden window: no console flashes up at sign-in. The .vbs
    embeds the absolute path of claude-watchdog.ps1, so re-run this installer
    whenever the project folder is moved.
#>

$ErrorActionPreference = 'Stop'

$Root       = Split-Path -Parent $MyInvocation.MyCommand.Definition
$Script     = Join-Path $Root 'claude-watchdog.ps1'
$StartupDir = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs\Startup'
$Launcher   = Join-Path $StartupDir 'claude-watchdog.vbs'

Write-Host ''
Write-Host '=== INSTALLING CLAUDE WATCHDOG ===' -ForegroundColor Cyan
Write-Host ''

if (-not (Test-Path -LiteralPath $Script)) {
    Write-Host "ERROR: $Script not found" -ForegroundColor Red
    exit 1
}

# 1) Stop any watchdog already running (e.g. from a previous install or folder)
$stopped = 0
foreach ($p in @(Get-CimInstance Win32_Process -Filter "Name='powershell.exe' OR Name='pwsh.exe' OR Name='wscript.exe'" -ErrorAction SilentlyContinue)) {
    if ($p.ProcessId -eq $PID) { continue }
    $cmd = [string]$p.CommandLine
    # Guard: never kill this installer or a concurrent uninstaller.
    if ($cmd -match 'install\.ps1') { continue }
    if ($cmd -match 'claude-watchdog\.ps1' -or $cmd -match 'claude-watchdog\.vbs') {
        try { Stop-Process -Id $p.ProcessId -Force -ErrorAction Stop; $stopped++ } catch { }
    }
}
Write-Host ("1. Previous watchdog processes stopped: {0}" -f $stopped)

# 2) Write the hidden launcher into the Startup folder
$vbs = @"
' Claude Watchdog launcher. Generated by install.ps1 - do not edit by hand.
' The 0 in Run means "hidden window": no console is shown.
Set sh = CreateObject("WScript.Shell")
sh.Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File ""$Script""", 0, False
"@
Set-Content -LiteralPath $Launcher -Value $vbs -Encoding ASCII
Write-Host ("2. Startup launcher written: {0}" -f $Launcher)

# 3) Start it now instead of waiting for the next sign-in
Start-Process -FilePath 'powershell.exe' `
    -ArgumentList @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-WindowStyle', 'Hidden',
                    '-File', $Script, '-StartDelaySeconds', '0') `
    -WindowStyle Hidden
Start-Sleep -Seconds 3
Write-Host '3. Watchdog started.'

Write-Host ''
Write-Host 'DONE. The watchdog now starts automatically with Windows.' -ForegroundColor Green
Write-Host 'Check it with status.bat or live-monitor.bat'
Write-Host ''
